const express = require("express");
const router = express.Router();
const User = require("../../models/User");
const School = require("../../models/School");
const Class = require("../../models/Class");
const Posting = require("../../models/Posting");
const File = require("../../models/File");
const bcrypt = require("bcryptjs");
const passport = require("passport");
const shortid = require('shortid');
 


// const fileUploader = require("../../configs/cloudinary/cloudinaryConfig");


// CREATE NEW SCHOOL (ADMIN) - AXIOS POST =========================================================

router.post('/api/setup/school', (req, res, next) => {

  const { schoolName, address, city, state, zip } = req.body;
  console.log("Frontend form data for school: ",req.body);
  creatorId = req.body.currentUser.userId
  console.log("Frontend data for currentuser: ",req.body.currentUser.userId);

  School.create({ schoolName, address, city, state, zip, creator: creatorId })
  .then((newSchool)=>{
    
    res.json({school: newSchool});
    // console.log(JSON.stringify(newSchool))
  })  
  .catch((err)=>{
    console.log(err)
    res.json({Msg: "An error occurred while adding the school. Please try again."})
  })

})

// CREATE NEW CLASS (Admin/Teacher) - AXIOS POST =========================================================

router.post('/api/setup/class', (req, res, next) => {
  
  const creator = req.user._id;
  const classroomCode = shortid.generate();
  
  console.log("Code generated by shortID", shortid.generate());

  const { className, teacher, schoolName, schoolId } = req.body;
  console.log("Frontend form data for school: " , req.body, creator );

  Class.create({ className, teacher, schoolName, schoolId, creator })
  .then((newClass)=>{
    
    res.json({msg: 'A new class has been added.', newClass});
    console.log(JSON.stringify(newClass))
  })  
  .catch((err)=>{
    console.log(err)
  })

})


// FIND USERS (Admin/Teacher) - AXIOS GET =========================================================

router.get('/api/getusers', (req, res, next) => {
  
  User.find()
  .then((usersFound)=>{
    
    res.json({msg: 'Users found', usersFound});
  })  
  .catch((err)=>{
    console.log(err)
  })

})



module.exports = router;